-- Drop stored procedures
DROP PROCEDURE IF EXISTS sp_InsertUser
DROP PROCEDURE IF EXISTS sp_UpdateUser
DROP PROCEDURE IF EXISTS sp_DeleteUser
DROP PROCEDURE IF EXISTS sp_GetUsers
DROP PROCEDURE IF EXISTS sp_InsertProduct
DROP PROCEDURE IF EXISTS sp_UpdateProduct
DROP PROCEDURE IF EXISTS sp_DeleteProduct
DROP PROCEDURE IF EXISTS sp_GetProducts
DROP PROCEDURE IF EXISTS sp_InsertCategory
DROP PROCEDURE IF EXISTS sp_UpdateCategory
DROP PROCEDURE IF EXISTS sp_DeleteCategory

DROP PROCEDURE IF EXISTS sp_DeleteNotification
DROP PROCEDURE IF EXISTS sp_DeleteSale
DROP PROCEDURE IF EXISTS sp_GetCategories
DROP PROCEDURE IF EXISTS sp_GetNotifications
DROP PROCEDURE IF EXISTS sp_GetSales
DROP PROCEDURE IF EXISTS sp_InsertSale
DROP PROCEDURE IF EXISTS sp_UpdateNotification
DROP PROCEDURE IF EXISTS sp_UpdateSale
DROP PROCEDURE IF EXISTS sp_InsertNotification
